### ISSUE TITLE
not working on Sequoia 15.2

### ISSUE THREAD

**Issue by fikrystilllearning** [lzhoang2801/OpCore-Simplify#83] opened 2024-12-20 10:02 UTC
![Uploading Screenshot 2024-12-20 at 02.01.14.png…]()

**Comment by fikrystilllearning** [comment] 2024-12-20 10:03
Last login: Fri Dec 20 02:00:52 on ttys000
/Users/fikry/Downloads/OpCore-Simplify-main/OpCore-Simplify.command ; exit;
fikry@Fikrys-MacBook-Pro ~ % /Users/fikry/Downloads/OpCore-Simplify-main/OpCore-Simplify.command ; exit;


























####################################################################
#                        Check for Updates                         #
####################################################################

SHA version information is missing in the sha_version.txt file.

Traceback (most recent call last):
  File "/Users/fikry/Downloads/OpCore-Simplify-main/OpCore-Simplify.py", line 344, in <module>
    update_flag = updater.Updater().run_update()
  File "/Users/fikry/Downloads/OpCore-Simplify-main/updater.py", line 64, in run_update
    latest_sha_version = self.get_latest_sha_version()
  File "/Users/fikry/Downloads/OpCore-Simplify-main/updater.py", line 32, in get_latest_sha_version
    latest_commit = self.github.get_latest_commit("lzhoang2801", "OpCore-Simplify") or {}
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fikry/Downloads/OpCore-Simplify-main/Scripts/github.py", line 18, in get_latest_commit
    for line in response.splitlines():
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by lzhoang2801** [comment] 2024-12-25 02:05
Duplicate of #81

**Closed by lzhoang2801** 2024-12-25 02:05 UTC
