### ISSUE TITLE
error 1

### ISSUE THREAD

**Issue by parvindergithub** [lzhoang2801/OpCore-Simplify#88] opened 2024-12-26 04:35 UTC
OpCore-Simplify.bat run as admin. got error 1  can`t understand  please help....
I am curious i want this for years  
your project is awesome  gr8 job

mention -- my bios is vanished ... trying to install no luck because of my laptop battery is dead...
OpCore-Simplify run without bios ???

![zz](https://github.com/user-attachments/assets/dfe02b02-337f-4274-9128-8dad28bca259)

**Comment by lzhoang2801** [comment] 2024-12-28 07:45
Duplicate of #81

**Closed by lzhoang2801** 2024-12-28 07:45 UTC
