### ISSUE TITLE
SHA version info missing

### ISSUE THREAD

**Issue by RicMing-sp** [lzhoang2801/OpCore-Simplify#84] opened 2024-12-21 05:50 UTC
Launching the bat file show the error SHA version information is missing.
Then process close 
![launch error SHA version](https://github.com/user-attachments/assets/0e64baa8-7ceb-4184-b962-ca4ee41864dd)

**Comment by lzhoang2801** [comment] 2024-12-25 02:05
Duplicate of #81

**Closed by lzhoang2801** 2024-12-25 02:05 UTC

**Comment by Mandaraxa** [comment] 2025-01-11 13:52
Hi,
Now it works for me, but unfortunately is useless, because I do not have Windows installed on this computer and have nowhere to install it. Hardware sniffer needs windows to generate the .JSON file. So I am in impass to generate the hardware report. But I wanted to let you know it works. Thank you for the hard work.
