### ISSUE TITLE
SHA version information is missing in the sha_version.txt file

### ISSUE THREAD

**Issue by Hank20123** [lzhoang2801/OpCore-Simplify#86] opened 2024-12-23 14:29 UTC
![Capture](https://github.com/user-attachments/assets/e71a655e-f94c-4f82-b4f4-ba0934cf9502)

**Comment by lzhoang2801** [comment] 2024-12-25 02:05
Duplicate of #81

**Closed by lzhoang2801** 2024-12-25 02:05 UTC
